const REQUEST_HEADER = {
  'Content-Type': 'application/json',
  'Accept': 'application/json'
};

const KEY_PERSIST_STORE = 'functor.guys';
const API_URL = process.env.REACT_APP_API_URL;
const PUBLIC_URL = process.env.REACT_APP_PUBLIC_URL;
const BASE_PATH =  process.env.REACT_APP_BASE_PATH;
const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN;
const FIREBASE_DATABASE_URL = process.env.REACT_APP_FIREBASE_DATABASE_URL;
const FIREBASE_PROJECT_ID = process.env.REACT_APP_FIREBASE_PROJECT_ID;
const FIREBASE_STORAGE_BUCKET = process.env.REACT_APP_FIREBASE_STORAGE_BUCKET;
const FIREBASE_MESSAGING_SENDER_ID = process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID;
const MAIN_COLOR = '#53bdf6';
const SECONDARY_COLOR = '#f79c5a';

export {
  REQUEST_HEADER,
  KEY_PERSIST_STORE,
  API_URL,
  PUBLIC_URL,
  BASE_PATH,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  MAIN_COLOR,
  SECONDARY_COLOR
}
